### ISSUE TITLE
Support for coverage 4.0

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/z3c.coverage#2]
[coverage.py 4.0](http://nedbatchelder.com//blog/201508/coveragepy_40b1.html) changes the format for .coverage files and introduces an API for accessing the data so perhaps we won't need to poke around in the private internals any more.

It'd be good to make sure z3c.coverage can work with coverage.py 4.0.

**Comment by agroszer** [comment]
had to nail coverage.py version < 4.0 to make winbot happy

**Comment by jensens** [comment]
nowadays this pin does hurt more than it helps. is this still a problem?

**Comment by mgedmin** [comment]
Nobody did any work to make z3c.coverage work with coverage >= 4.0.0, AFAIK.

**Comment by LRGH** [comment]
I made a pull request, with a minimal patch that makes z3c.coverage work with recent coverage.py, at least for my own usage.
